# Monitor Configuration. https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,    1920x1200@144,   1920x0, 1.33

monitorv2 {
	output = HDMI-A-1
	mode = 1920x1080@144
	position = 0x0
	scale = 1.0
	bitdepth = 10

	# cm = auto

	# sdr_max_luminance = 200
	# sdr_min_luminance = 0.005

	# max_luminance = 400
	# min_luminance = 0.005
}

render {
	cm_auto_hdr = 0
	cm_fs_passthrough = 0
}

# Startup applications
# exec-once = spotify & (sleep 3 && kitty cava)
# exec-once = hyprctl dispatch exec [workspace 1 silent] -- fluent-reader --ozone-platform-hint=auto
exec-once = hyprctl dispatch exec [workspace 1 silent] thunderbird
exec-once = hyprctl dispatch exec [workspace 1 silent] obsidian
exec-once = hyprctl dispatch exec [workspace 2 silent] slack
exec-once = hyprctl dispatch exec [workspace 2 silent] discord
exec-once = kdeconnectd # KDE CONNECT!
# exec-once = eiskaltdcpp-gtk

workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1

# Window rules
# Spotify with cava in background
# http://wiki.hyprland.org/Useful-Utilities/App-Clients/#spotify for spotify windowrules
# windowrulev2 = opacity 0.7 0.7,initialTitle:^Spotify, # Transparency
# windowrulev2 = float,initialTitle:^Spotify,           # Float window
# windowrulev2 = center 1,initialTitle:^Spotify,        # Center window
# windowrulev2 = noborder,initialTitle:^Spotify,        # Remove window border
# windowrulev2 = workspace 1,initialTitle:^Spotify,     # Confine to workspace 1
# windowrulev2 = rounding 15,initialTitle:^Spotify,     # Increase border rounding

windowrule = no_initial_focus on, match:class [Ff]luent-reader
windowrule = no_initial_focus on, match:class thunderbird

windowrule = no_initial_focus on, match:class [Dd]iscord
windowrule = workspace 2, match:class [Dd]iscord
windowrule = no_initial_focus on, match:class [Ss]lack
windowrule = workspace 2, match:class [Ss]lack

# Obsidian
windowrule = no_initial_focus on, match:class [Oo]bsidian

